//go:build !ignore_autogenerated

/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and redis-operator-cop contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsProperties) DeepCopyInto(out *MetricsProperties) {
	*out = *in
	if in.PodMonitor != nil {
		in, out := &in.PodMonitor, &out.PodMonitor
		*out = new(PodMonitorProperties)
		**out = **in
	}
	if in.PrometheusRule != nil {
		in, out := &in.PrometheusRule, &out.PrometheusRule
		*out = new(PrometheusRuleProperties)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsProperties.
func (in *MetricsProperties) DeepCopy() *MetricsProperties {
	if in == nil {
		return nil
	}
	out := new(MetricsProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMonitorProperties) DeepCopyInto(out *PodMonitorProperties) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMonitorProperties.
func (in *PodMonitorProperties) DeepCopy() *PodMonitorProperties {
	if in == nil {
		return nil
	}
	out := new(PodMonitorProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusRuleProperties) DeepCopyInto(out *PrometheusRuleProperties) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]v1.Rule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusRuleProperties.
func (in *PrometheusRuleProperties) DeepCopy() *PrometheusRuleProperties {
	if in == nil {
		return nil
	}
	out := new(PrometheusRuleProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisOperator) DeepCopyInto(out *RedisOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisOperator.
func (in *RedisOperator) DeepCopy() *RedisOperator {
	if in == nil {
		return nil
	}
	out := new(RedisOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RedisOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisOperatorList) DeepCopyInto(out *RedisOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RedisOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisOperatorList.
func (in *RedisOperatorList) DeepCopy() *RedisOperatorList {
	if in == nil {
		return nil
	}
	out := new(RedisOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RedisOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisOperatorSpec) DeepCopyInto(out *RedisOperatorSpec) {
	*out = *in
	out.Spec = in.Spec
	out.Image = in.Image
	in.KubernetesProperties.DeepCopyInto(&out.KubernetesProperties)
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricsProperties)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisOperatorSpec.
func (in *RedisOperatorSpec) DeepCopy() *RedisOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(RedisOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisOperatorStatus) DeepCopyInto(out *RedisOperatorStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisOperatorStatus.
func (in *RedisOperatorStatus) DeepCopy() *RedisOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(RedisOperatorStatus)
	in.DeepCopyInto(out)
	return out
}
